spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:mysql://localhost:3306/chyou?serverTimezone=UTC&allowMultiQueries=true
    url: jdbc:log4jdbc:mysql://chyou.co.kr:3306/juyoung32?serverTimezone=UTC&allowMultiQueries=true
    username: juyoung32
    password: healingchurch123
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*-mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring.thymeleaf.cache: false
logging:
  level:
    org:
      springframework:
        security: INFO
        web: DEBUG

debug: true